/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vmunlucinkmblktmexmr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdW5sdWNpbmttYmxrdG1leG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjYxNTYsImV4cCI6MjA5MDA0MjE1Nn0.xS0wHOZIhf73Fz-RpmVszjPKaKHQ-6bpMZbpIvqizD8"